# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Petish-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Petish-iOS

pod 'gRPC-Core', '1.21.0'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'


end

